spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/et001springbootdb-local
    password: ''
  application:
    name: ET001FirstSpringboot
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8089'